### ISSUE TITLE
Reverse for 'peer_group_list' not found

### ISSUE THREAD

**Issue by jeyriku** [k01ek/netbox-bgp#109]
**NetBox version**
What version of NetBox are you currently running?
v3.3.3

**Describe the bug**

<class 'django.urls.exceptions.NoReverseMatch'>
Reverse for 'peer_group_list' not found. 'peer_group_list' is not a valid view function or pattern name.

Python version: 3.8.10
NetBox version: 3.3.3

**To Reproduce**
1. Go to 'Plugins'
2. Click on 'Peer Groups'

![image](https://user-images.githubusercontent.com/62744576/193309527-b4b63a9a-6b00-480e-b2fa-dcecd85067c5.png)

Thanks in advance for your kind help.
Jeremie

**Comment by k01ek** [comment]
Hi @jeyriku ! What plugin version do you use?

**Comment by jeyriku** [comment]
Hi @k01ek,

I use plugin version netbox-bgp  0.8.1

Regards,

**Comment by k01ek** [comment]
Is it new installation of the plugin or you used older plugin version before ?

**Comment by jeyriku** [comment]
Hi Nilolay,

 

Actually, it is a new installation of the plugin.

 

Thanks again for your help !

 

Jérémie Rouzet

+33 623701549

---

 

 

De : Nikolay Yuzefovich ***@***.***>
Répondre à : k01ek/netbox-bgp ***@***.***>
Date : vendredi 13 janvier 2023 à 08:17
À : k01ek/netbox-bgp ***@***.***>
Cc : Jeremie Rouzet ***@***.***>, Mention ***@***.***>
Objet : Re: [k01ek/netbox-bgp] Reverse for 'peer_group_list' not found (Issue #109)

 

Is it new installation of the plugin or you used older plugin version before ?

**Comment by k01ek** [comment]
Can you provide traceback from logs?
