### ISSUE TITLE
routing policy custom match rule should allow any JSON value

### ISSUE THREAD

**Issue by mkurjanski** [k01ek/netbox-bgp#111]
**NetBox version**
v3.3.5 / plugin 0.8.1

**Describe the bug**
I'd like to add a custom match rule allowing to match based on community lists.
Unfortunately it looks like currently only few keys are allowed in the custom policies ('ip_address', 'community') or the field will display '{}'

**To Reproduce**
1. Go to any routing-policy
2. Click on '+ Rule'
3. Fill in the mandatory fields with any allowed values
4. Scroll down to 'Custom Match'
5. Paste: '{"community_list": "MY_LIST"}'
6. Click 'Create'
7. The 'Custom Match' field stays empty

**Screen shot**
![image](https://user-images.githubusercontent.com/34099713/196940795-b3db87f5-b640-40c4-85e0-f45eaf989180.png)

**Expected behavior**
The custom match field should allow any custom JSON value.

**Comments**
It looks like this is only a cosmetic issue that affects the displayed field. If I edit newly created policy rule entry it shows the JSON value just fine.

**Comment by k01ek** [comment]
#181
