### ISSUE TITLE
Add compatibility for NETBOX 3.3.5

### ISSUE THREAD

**Issue by WAN4YOU** [k01ek/netbox-bgp#113]
Hello, 
it is possible to add the compatibility with NETBOX 3.3.5 
as soon as you install it and start NETBOX, NETBOX remains crashed impossible to access the web interface 

An update would be welcome 

Thanks in advance

**Comment by ryanmerolle** [comment]
Version 0.8.1 works with NetBox 3.3.x

My NetBox is currently at 3.3.9 and it works fine with that version of netbox-bgp.

@WAN4YOU Upgrade your plugin version and maybe even your NetBox version to see if it resolves it.

I think this issue can be closed.

**Comment by k01ek** [comment]
Hi @WAN4YOU ! Can you provide logs for  NetBox crash?
