### ISSUE TITLE
Filtering on custom fields on BGP sessions doesn't work

### ISSUE THREAD

**Issue by bgianpetro** [k01ek/netbox-bgp#119]
**NetBox version**
3.3.10

**Describe the bug**
Filtering on custom fields on BGP sessions returns all objects

**To Reproduce**
1. Create a custom field on BGP sessions (e.g., create CF named 'testfield' as a boolean)
2. Set the test field value (set 'testfield' on a BGP session to 'true')
3. Search on the created field's value (go  to BGP sessions -> Filter, and select 'true' under the 'testfield' CF)
4. Results will show all BGP sessions

**Expected behavior**
BGP Sessions would be filtered only the value of the custom field.

**Screenshots**
I basically did the exact thing in the "To Reproduce" section and here are the results (note that I added the "testfield" column so you can see the value):

![image](https://user-images.githubusercontent.com/7749432/208154180-62447485-58c2-4d4e-9a4b-9287f68697ac.png)

**Additional context**
I also attempted this via the API and the results were the same.  Wasn't sure if this was a Netbox issue, Netbox BGP issue, or personal issue, but I figured I'd start here.

**Comment by bgianpetro** [comment]
I found this to be the case for all objects on this plugin so I did some digging.  I believe it's because the `FilterSet` objects aren't inheriting from `NetBoxModelFilterSet`. Working on a fix now.

**Comment by jwbensley** [comment]
Hey @bgianpetro did you fix your issue? I'm now seeing this issue: https://github.com/k01ek/netbox-bgp/issues/133

Do you think they are related?

**Comment by bgianpetro** [comment]
Hello! Yeah, I fixed my issue with the referenced PR.  It appears that yours is something in the match logic -- I'll have a look.
