### ISSUE TITLE
Feature Request: BGP Peer Type attribute

### ISSUE THREAD

**Issue by falz** [k01ek/netbox-bgp#12]
Was happy to find this plugin, have not yet tested it. I would suggest adding a 'Peer Type' where it's one of these. Perhaps configurable choices with these as defaults, but at bare minimum:

* Customer
* Peer
* Transit

This is helpful if one were to use this to automatically create peering policy configurations, which would be impossible to do without knowing the relationship of the peer.

Think localpref as an example of one attribute one would set based on peer type, which is typically higher for customer and settlement free peers than and lower for paid transit.

**Comment by falz** [comment]
Additional comment that the thinking behind this request circumvents the need for issue https://github.com/k01ek/netbox-bgp/issues/7 for our particular use case.

Instead of documenting import/export policies per-peer, we would envision that we would achieve the same thing based on peer type, for the most part. Think "all settlement free peers get this same policy". That policy should of course have some customization based on prefixes and their IRR records, but still do-able using the peers name as a variable for that policy.

We would of course still find issue 7 useful for one off custom configs however.

**Comment by k01ek** [comment]
Hi @falz ! I am going to do #4. It should help you. Some part of this functionality is already in the code.

**Comment by falz** [comment]
Sounds good, hope you keep this issue on the radar as well as quite frankly it's less work if one is using this methodology to auto create config stuffs.

**Comment by pspdbx** [comment]
> Additional comment that the thinking behind this request circumvents the need for issue #7 for our particular use case.
> 
> Instead of documenting import/export policies per-peer, we would envision that we would achieve the same thing based on peer type, for the most part. Think "all settlement free peers get this same policy". That policy should of course have some customization based on prefixes and their IRR records, but still do-able using the peers name as a variable for that policy.
> 
> We would of course still find issue 7 useful for one off custom configs however.

Wouldn't work for our use case at the moment... we'd rather have the granular per-peer routing policy configuration. Perhaps at some point in the future when we have all our configs cleaned up, maybe it will work this way. Regardless, a peer type is definitely useful.
