### ISSUE TITLE
netboxcommunity/netbox:latest throwing error Plugin netbox_bgp requires NetBox maximum version 3.3.99.

### ISSUE THREAD

**Issue by mhill1988** [k01ek/netbox-bgp#128]
**NetBox version**
3.4 (Docker Container)

**Describe the bug**
```netbox-docker-netbox-1               | django.core.exceptions.ImproperlyConfigured: Plugin netbox_bgp requires NetBox maximum version 3.3.99.```
Looks like when pulling the netbox_bgp plugin from docker.io (netboxcommunity/netbox:latest) its erroring out with the above. 

**To Reproduce**

**Expected behavior**
Would expect the netbox-bgp image on netboxcommunity/netbox:latest to be compatible with the latest netbox image? 

**Screenshots**

**Additional context**
Super noob here, may be user error. Any help is appreciated.

**Comment by eawain** [comment]
Have run into this as well on a upgrade on a non docker install.
Last version that seems to work or be supported it v 3.3.10

**Comment by eawain** [comment]
Think I found the culprit on LINE 15 of 

/opt/netbox/venv/lib/python3.10/site-packages/netbox_bgp/__init__.py 

max_version = '3.3.99'

**Comment by kuhball** [comment]
There's already a PR #126 including a netbox version bump. We're all waiting for it to be merged :fist:

**Comment by MajesticFalcon** [comment]
Hoping this comes soon!
