### ISSUE TITLE
Add option to disable top level menu

### ISSUE THREAD

**Issue by ryanmerolle** [k01ek/netbox-bgp#129]
**Is your feature request related to a problem? Please describe.**
Some netbox admins want the option to use enable or disable (ie go back to the original menu under plugins).

**Describe the solution you'd like**
I recommend a configuration option similar to https://github.com/ryanmerolle/netbox-acls/pull/113

**Describe alternatives you've considered**
Close this issue and not support the option.

**Comment by k01ek** [comment]
It's done, i just forget to change readme. 
https://github.com/k01ek/netbox-bgp/commit/f5d905ddbcd65fb8b6f380e2b857dd5b382ac16a
