### ISSUE TITLE
Search for "=" performs "in"/"contains" instead of "=="/"exact match"

### ISSUE THREAD

**Issue by jwbensley** [k01ek/netbox-bgp#133]
**NetBox version**
What version of NetBox are you currently running? 

v4.3.4 + BGP plugin version 0.9.0

**Describe the bug**

When searching for BGP sessions with a custom field which has a specific value, the search returns all BGP sessions with that value, but also all BGP session with have that value as a sub string.

I have a custom field called `as_set`. I have two test BGP sessions. One of them as `as_set` value `AAAAAA`, the other has an `as_set` value `AAA`. If I search for `AAAAAA` only one of the BGP sessions is returned. If I search for `AAA` both are returned.

**To Reproduce**
See screenshots, I am using the API.

Here we see that searching for `AAAAAA` only returns one BGP session:

![grafik](https://user-images.githubusercontent.com/1025875/226420978-4e68afc7-66bf-432b-96a0-a39b2806109e.png)

Here we see that searching for `AAA` returns both BGP sessions:

![grafik](https://user-images.githubusercontent.com/1025875/226421120-d1bcbafd-63fd-4477-89a3-da69e39322ec.png)

**Expected behavior**

Because I am using `=` in the query I expect an exact match, not a sub-string match.

**Screenshots**

**Additional context**

**Comment by bgianpetro** [comment]
Filtering behavior on a custom field is a property of the custom field; if you want to change the filtering to match exactly, change the custom field "Filter Logic" from "loose" to "exact".  I tested this on a custom field on BGP sessions using the exact values you have above and it works as expected with the custom field set to "exact".

**Comment by jwbensley** [comment]
@bgianpetro thanks for your response. This resolves my issue.
