### ISSUE TITLE
Seems 0.10.0 release not pushed to pypi

### ISSUE THREAD

**Issue by dmulyalin** [k01ek/netbox-bgp#138]
Was trying to install release 0.10.0 but failed to pull it from pypi, would it be possible to publish it to pypi as well please.

**Comment by stuntguy3000** [comment]
The runner is stuck

https://github.com/k01ek/netbox-bgp/actions/runs/4944469485/jobs/8839977933

**Comment by k01ek** [comment]
Thanks!
