### ISSUE TITLE
Netbox 3.5 API documentation error after installed netbox-bgp plugin

### ISSUE THREAD

**Issue by dmulyalin** [k01ek/netbox-bgp#141]
**NetBox version**
What version of NetBox are you currently running? - Netbox 3.5.1

**Describe the bug**
After added Netbox-BGP plugin Nebtox swagger UI for API documentation gives this error:
```
response status is 500 /api/schema/
```

After disabling netbox bgp plugin Swagger UI started loading fine.

**To Reproduce**
Install netbox bgp with netbox 3.5 and go to Swagger UI API documentation

**Expected behavior**
API documentation loads fine

**Comment by k01ek** [comment]
#139
