### ISSUE TITLE
Increase length of BGP Name

### ISSUE THREAD

**Issue by jwbensley** [k01ek/netbox-bgp#145]
**Is your feature request related to a problem? Please describe.**
We are unable to put anything useful into the BGP name because it is too small "64 characters").

**Describe the solution you'd like**
Can the BGP session name field be increased to 256 characters?

**Describe alternatives you've considered**
Currently we are having to add custom fields to work around this, but I think/hope it would be a simple change, and I see no reason for limiting BGP names to such a short value.

**Additional context**
None.

**Comment by k01ek** [comment]
Why you don't use description field?

**Comment by jwbensley** [comment]
We are putting some data into description and some into custom fields. But it raises the question, what's the point in having a name field if it's too short to stored the name of the BGP session? So either the name field should be removed because it's not needed, or the length should be increased because it's too small.

**Comment by jwbensley** [comment]
Hey @k01ek what I forgot to mention in my last comment, is that we can't leave the Name field blank, it is a required field. But it's too short to store the customer name, or the name of the remote network. So we are not short what to store in this field, and it is a required field.

**Comment by k01ek** [comment]
I can increase session name field in the next release, it is not problem
