### ISSUE TITLE
NetBox API schema breaks again in netbox-bgp 0.11.0 with NetBox 3.6.3

### ISSUE THREAD

**Issue by eu-tomas** [k01ek/netbox-bgp#154]
**NetBox version**
3.6.3 (possibly all 3.6 versions)

**Describe the bug**
The issue that was fixed in #139 seems to have returned since upgrading to NetBox 3.6.x and the latest netbox-bgp plugin (0.11.0)

**To Reproduce**
See issue #139 for more details.
1. Install NetBox 3.6.3 with netbox-bgp 0.11.0
2. Access /api/schema/?format=json via a browser
3. Error message:
```
<class 'ValueError'>

list.remove(x): x not in list

Python version: 3.9.16
NetBox version: 3.6.3
Plugins: 
  netbox_bgp: 0.11.0
```

**Expected behavior**
When accessing /api/schema/?format=json, I am expecting to see a JSON schema representation of the NetBox data model. This is necessary for the netbox inventory ansible plugin to work.

**Screenshots**
See #139

**Additional context**
Not tested with other 3.6 versions, only with 3.6.3 and with netbox-bgp 0.11.0
As before in #139, removing/disabling the netbox-bgp plugin resolves the issue.

**Comment by balpoint** [comment]
With a normal install of netbox how can we install this fix, could someone explain that to me ?

**Comment by GSeiNet** [comment]
I think, i have simalar problem:
Netbox 3.6.4
BGP 0.11.0

If i try to access swagger-ui -> Error "Failed to load API definition"

This behavior was documented and solved at:

[swagger-ui to get "Failed to load API definition" · Issue #12514 · netbox-community/netbox · GitHub](https://github.com/netbox-community/netbox/issues/12514)

**Comment by huttmf** [comment]
Has this fix been merged to the main branch yet? If not which release do you expect this to be in? Thx.

**Comment by rboucher-me** [comment]
@k01ek does your [fix](https://github.com/k01ek/netbox-bgp/commit/5acdba4d54b5e8d4260a3f63455701f680795005) adequately address this issue? if so, any chance it can be merged? if not, how might we help? thanks!

**Comment by k01ek** [comment]
sorry guys for the latency, i was planning to add some new features in last release, but could not find time

**Comment by rboucher-me** [comment]
Thank you! Much appreciated!

Richard

**Comment by marcosmas28** [comment]
> Has this fix been merged to the main branch yet? If not which release do you expect this to be in? Thx.

Hi, I have the same question as @huttmf; is this fix available in the main branch? I think no because I'm still facing the issue.
Thanks for any comment on this.

**Comment by marcosmas28** [comment]
I'm sorry. I just found the version 0.11.1 with the fix.
Thanks!
