### ISSUE TITLE
Tags for Prefix List Rule

### ISSUE THREAD

**Issue by janhlavin** [k01ek/netbox-bgp#157]
**NetBox version**
3.6.3

**Describe the bug**
Tags is not saving for "Prefix List Rule"

**To Reproduce**
1. Create TAG (Customization - Tags)
2. Create PREFIX LIST (BGP - Prefix Lists)
3. Create PREFIX LIST RULE (BGP - Prefix Lists - "created PL") with "created TAG"

**Expected behavior**
Save selected tags to "Prefix List rule"

**Comment by pl0xym0r** [comment]
If you do it through forms, PR #156 will solve it. Workaround is to create PL rules with tags through API

**Comment by k01ek** [comment]
fixed by @pl0xym0r
