### ISSUE TITLE
Add support for BGP passwords

### ISSUE THREAD

**Issue by rvtipper** [k01ek/netbox-bgp#159]
Hi - thanks for your work on this plugin.

**Is your feature request related to a problem? Please describe.**
We have many peerings with MD5 authentication configured on the peering. It would be great to be able to have this included in the session data in netbox-bgp

**Describe the solution you'd like**
Having an additional field for the password stored in encrypted form with the ability to decrypt would be great. But just having a Yes / No option to record the existence of a password on a peering would also be very helpful. This would help guide our config scripts if we need to try find the password we store elsewhere.

**Comment by pl0xym0r** [comment]
Creating a custom field wouldn't solve your need? on peer-goup or session object ?

**Comment by rvtipper** [comment]
Hi - ok I can proceed like that, thanks.
