### ISSUE TITLE
BGP routing-policy object, Custom Match value is represented as list instead of string.

### ISSUE THREAD

**Issue by vladimirs-git** [k01ek/netbox-bgp#166]
**NetBox version**
Netbox=v3.5.4
netbox-bgp=v0.11.1

**Describe the bug**
In BGP routing-policy object, Custom Match value is represented as list instead of string.
[Routing Policy Rules](http://127.0.0.1:8000/plugins/bgp/routing-policy-rule/) display Custom Match value improperly

**To Reproduce**
```python
api_path = "http://127.0.0.1:8000/api/plugins/bgp/routing-policy-rule/3/"
data = {
    "id": 3,
    "tags": [],
    "custom_fields": {},
    "display": "rm_prod_univ_in: Rule 10",
    "created": "2023-12-05T08:39:42.274517Z",
    "last_updated": "2023-12-05T08:57:22.580838Z",
    "custom_field_data": {},
    "index": 10,
    "action": "permit",
    "description": "",
    "continue_entry": null,
    "match_custom": {
        "community": "cl_rix1_3_150"
    },
    "set_actions": {
        "local-preference": 150
    },
    "routing_policy": 5,
    "match_community": [],
    "match_ip_address": [],
    "match_ipv6_address": []
}
```

**Expected behavior**
Expected string value instead of list of characters.

**Screenshots**
![rp_rule1](https://github.com/k01ek/netbox-bgp/assets/56936092/262db62d-2e3d-4db3-b993-9ff67b630c38)
![rp_rule2](https://github.com/k01ek/netbox-bgp/assets/56936092/af68e512-dd5f-434a-94b0-ebf5468bf183)

**Comment by pl0xym0r** [comment]
From what is written in the code, community should be a list. It could make sense because you could match a list of them.
Try "match_custom": {"community": ["cl_rix1_3_150"]} and you 'll see.

**Comment by vladimirs-git** [comment]
In this case, the example at the bottom of the form is incorrect.
Instead of `{"ip nexthop": "1.1.1.1"}` should be `{"ip nexthop": ["1.1.1.1"]}`
![image](https://github.com/k01ek/netbox-bgp/assets/56936092/12f06a54-21d5-42d8-bc7c-6af5ab23c234)

**Comment by pl0xym0r** [comment]
Well, only "community", "ip address" and "ipv6 address" keys are concerned as these 3 parameters are available in the object itself (above the custom match). 
Goal is to append the object parameters with eventual custom match.
