### ISSUE TITLE
Connect prefix lists directly to sessions

### ISSUE THREAD

**Issue by AleksBelytskyi** [k01ek/netbox-bgp#176]
**Is your feature request related to a problem? Please describe.**
That's quite a common configuration to connect the prefix list directly to the BGP neighbor/peer without creating routing policies. At the moment that's not possible.

**Describe the solution you'd like**
It should be possible to have extra fields while editing BGP sessions such as: "Import prefixes" and "Export prefixes" with a drop-down of existing prefix lists. Also, it's good to see related BGP sessions on the prefix list view page.

**Describe alternatives you've considered**
It's possible to use a custom field for that but then we cannot see to what BGP sessions the prefix list is assigned.

**Additional context**
None

**Comment by AleksBelytskyi** [comment]
Hello,
Any suggestions on this?
Thanks

**Comment by k01ek** [comment]
Hi @AleksBelytskyi !  Prefix list filter is part of the routing policy. it's just configured in another piece of config (for Cisco), but in fact it is routing policy.

**Comment by AleksBelytskyi** [comment]
Hi @k01ek,
First of all, thank you for your response. I appreciate it.
You are right. The prefix list filter can be included in the routing policy, but it can also be used separately and attached to the BGP peer directly. This means that general prefix filters can be applied to group routing policies, while unique prefix filters can be applied directly to individual peers. Many vendors, including Cisco, Arista, HP, and Huawei, support this functionality. (as far as I know, JunOS applies prefix filters through routing policies only). 
Therefore, incorporating this functionality into the BGP plugin will provide more flexibility. Additionally, I believe that implementing it should not require a significant amount of effort (maybe I'm wrong :)

**Comment by k01ek** [comment]
#181
