### ISSUE TITLE
Feature Request: Bulk import

### ISSUE THREAD

**Issue by liquid-metal** [k01ek/netbox-bgp#21]
It would be quite useful to have API endpoints for bulk creation, Update and deletion of all objects (Sessions, ASNs, Policies, Communites)
Related to this, it would be nice to have a CSV Bulk import in the UI as well

**Comment by k01ek** [comment]
I agree with you. It is in the plan.

**Comment by dmulyalin** [comment]
It would be great to have CSV import capabilities, maybe communities would be a good start.

**Comment by k01ek** [comment]
#181
