### ISSUE TITLE
Feature Request: Prefix & IP relationships

### ISSUE THREAD

**Issue by ryanmerolle** [k01ek/netbox-bgp#25]
It would be nice to track expected prefixes and advertised prefixes on a BGP session.

As an FYI host routes cannot be added as a prefix hence why IP linkage/logic for host routes will need to be created.

**Comment by k01ek** [comment]
Hi @ryanmerolle! I don't quite understand what your goal is but perhaps routing policy rules would be useful for this.

**Comment by ryanmerolle** [comment]
Thanks for all the hard work!
