### ISSUE TITLE
ASN to device and vrf relationship

### ISSUE THREAD

**Issue by vladsker** [k01ek/netbox-bgp#36]
A small suggestion for BGP ASN model: this plugin uses tenants, but for some reason missing BGP ASN to device and BGP ASN to VRF relationship. 

This might also change view on https://github.com/k01ek/netbox-bgp/issues/19, since we can reuse the same ASN number in the different VRFs. for example.

What is your opinion on this?

**Comment by jlanclos** [comment]
It is also possible to have multiple vrf's with the same ASN, so it would be better to associate vrf at the BGP Session level.

**Comment by k01ek** [comment]
i think ASN should not have connection to VRF
