### ISSUE TITLE
Add a field to represent BGP session state like Open, Idle, Established

### ISSUE THREAD

**Issue by pspdbx** [k01ek/netbox-bgp#39]
The BGP session table has a 'Status' field, which represents the intended/operational status of a BGP session. It would be great if we also had a 'State' field that represents the state of the BGP session, such as Open, Connect, Active, Idle, Established

Details: https://www.ciscopress.com/articles/article.asp?p=2756480&seqNum=4

**Comment by k01ek** [comment]
Hi @pspdbx! Thanks for the feedback. I think it is very hard to sync the state between a real BGP session and an object. In what cases it can be useful?

**Comment by pspdbx** [comment]
I've thought more about this, and I agree with you. I suppose Netbox is not the right tool for displaying BGP session state. A monitoring tool with a decent dashboard/GUI would serve better. 

My original thought about wanting this feature is because the systems that represents intended state (Netbox) and the actual state (a monitoring system like LibreNMS or NetSpyGlass) are not tightly integrated. Neither tool presents the full picture: User looking at a monitoring system can't tell if the BGP sessions that are down are a cause for concern or not, unless the user also looks at Netbox (your plugin) and correlates the information. That process is very manual and painful when there are lots of sessions. This problem still remains to be solved, but to do it in this plugin is not the right way. We shall develop better integration between Netbox and our monitoring system to achieve the desired effect.

**Comment by k01ek** [comment]
@pspdbx the bgp session has state attribute(active, offline, planed) so you can use it. For example, enable trigger in the monitoring sistem only for session wich has active state in the netbox.

**Comment by k01ek** [comment]
You can use webhooks to sync bgp session status from netbox to your monitoring system, if it has api.

**Comment by pspdbx** [comment]
> @pspdbx the bgp session has state attribute(active, offline, planed) so you can use it. For example, enable trigger in the monitoring sistem only for session wich has active state in the netbox.

Yes, thats the integration work I was referring to.
