### ISSUE TITLE
Feature Request: Add BGP Peer Groups

### ISSUE THREAD

**Issue by ryanmerolle** [k01ek/netbox-bgp#4]
Add a to the data model the ability to track BGP Peer Groups.

BTW really slick setup!  Thanks for sharing!

**Comment by k01ek** [comment]
Do you want to track BGP Peer Groups as a particular model or as a new field in the BGP Session model?

**Comment by ryanmerolle** [comment]
I thinks it's just the ability to define a peer-group and associate that to a BGP session.

**Comment by omri-ice** [comment]
It'll also make sense to add the ASN, and import/export policies fields to a peer group since most devices support this feature.
