### ISSUE TITLE
Expand Search fields in BGP Session List view to include addresses and Name

### ISSUE THREAD

**Issue by pspdbx** [k01ek/netbox-bgp#40]
Hello,

The Search column in the BGP sessions list view doesn't offer a way to search by Name, Device, Remote Address, Local Address. Having these fields will help a lot when there are a lot of sessions (over 20K) and we are only interested in some of them.

Please include a way to search by: Name, Device, Remote Address, Local Address

**Comment by k01ek** [comment]
Hi @pspdbx ! You can search by name using first field (search). I will add Device field to search form in next release. 
As for remote/local address, you need to clarify how you want to use them.

**Comment by k01ek** [comment]
I have added just a char fields for search by local and remote IP, it should be enough.
