### ISSUE TITLE
Support Netbox 2.11.4

### ISSUE THREAD

**Issue by brotherdust** [k01ek/netbox-bgp#41]
https://github.com/k01ek/netbox-bgp/blob/0db73d5244785cf94a8b14eb22e67b46aecbd8c2/netbox_bgp/__init__.py#L15

I can't install the plugin because the maximum version is hard-coded to 2.11.3, referenced in the file above. can you please increment this and release on PyPi?
Thanks!

**Comment by k01ek** [comment]
Hi @brotherdust ! I am going to test the plugin with other versions and then release it.
