### ISSUE TITLE
BGP Session Edit view is too slow does not work consistently

### ISSUE THREAD

**Issue by pspdbx** [k01ek/netbox-bgp#44]
**NetBox version**
2.11.2

**Describe the bug**
After a BGP Session is created, when I try to edit it by clicking on the Edit button (which tries to take me to https://<netbox url>/plugins/bgp/session/<pk>/edit/) the edit BGP session page takes a very long time to load, and only loads sometimes. Most of the time, the page just hangs. 

**To Reproduce**
1. Create a BGP session via the GUI
2. Click on the BGP session created, to view Details of the Session.
3. Click on the Edit button
4. Observe behavior: Does the Edit session page load quickly? 

**Expected behavior**
The Edit BGP Session page loads as quickly as the Details view of the BGP session.

**Screenshots**
n/a

**Additional context**
The problem doesn't seem to be load/database size related. This behavior is observed both in our Production env as well as in Dev env. The total number of BGP sessions is only 5, so its not about number of entries in the BGP Session table. We do however have 2000 IP Address objects in Production, and 500 IP Address objects in Dev.

**Comment by k01ek** [comment]
#66
