### ISSUE TITLE
Support version  2.11.7

### ISSUE THREAD

**Issue by hiddenman** [k01ek/netbox-bgp#47]
Hi,

Thank you for the great product. Could you please test and update to support the current netbox release = 2.11.7?

`django.core.exceptions.ImproperlyConfigured: Plugin netbox_bgp requires NetBox maximum version 2.11.6.`

Thank you.

**Comment by greenfox878** [comment]
Hi,
Just kindly reminder. netbox v2.11.8 released to days ago

**Comment by k01ek** [comment]
yaaa, I am going to test 2.11.8 today

**Comment by hiddenman** [comment]
> yaaa, I am going to test 2.11.8 today

Ah, yes. Please, update to 2.11.8 :-)  I'm already using it and everything is fine.
