### ISSUE TITLE
v3.0-beta1 version support

### ISSUE THREAD

**Issue by hiddenman** [k01ek/netbox-bgp#51]
Hi,

Today 3.0beta1 has been released and it has many new features and UI.
Please, update you plugin to support this version.

Thank you.

**Comment by ryanmerolle** [comment]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by k01ek** [comment]
Thank you @ryanmerolle !

**Comment by hiddenman** [comment]
> Thank you @ryanmerolle !

Hi,

Btw, this Thursday there will be a 3.0.0 release.

**Comment by salman79uk** [comment]
Hi,

Any ETA on this support for 3.0.0?

Kind regards,

**Comment by k01ek** [comment]
Hi folks! I'm going to update a couple of non-public plugins and then for this one. I don't know how long it might take.

**Comment by packet33** [comment]
Just dropping in to see if there is any ETA yet. It's been about 2 weeks since you last commented :)
