### ISSUE TITLE
BGP plugin permission configuration support

### ISSUE THREAD

**Issue by karlism** [k01ek/netbox-bgp#53]
**Is your feature request related to a problem? Please describe.**
NetBox BGP plugin lacks permission configuration and is only available to users with superuser permissions. In our case we use group permissions to assign specific permissions to them (e.g. some users have only read only access, some do not have access to secrets etc.). While using BGP plugin it is only possible to assign all (superuser) or nothing.

**Describe the solution you'd like**
NetBox plugins support permission management so it should be possible to add support for that to BGP plugin.

**Describe alternatives you've considered**
There aren't really any other alternatives besides giving full access to users that need any access to BGP plugin.

**Additional context**
https://ttl255.com/developing-netbox-plugin-part-5-permissions-and-api/

**Comment by k01ek** [comment]
Hi @karlism ! The plugin supports NetBox permissions mechanism which allows you to hide actions (view, add, change, delete) to any object. All you need to do is add permissions in the admin interface and append it to users or groups.

**Comment by karlism** [comment]
Thanks, I've found where I can configure permissions!
