### ISSUE TITLE
4 byte ASN support

### ISSUE THREAD

**Issue by tcpcyn** [k01ek/netbox-bgp#59]
**Is your feature request related to a problem? Please describe.**
Does the ASN value support 4 byte numbers?

**Describe the solution you'd like**
Would like support of 4 byte ASN values if not supported.

**Describe alternatives you've considered**
I don't know if there are alternatives, please let me know.

**Additional context**
none.

**Comment by k01ek** [comment]
Hi @tcpcyn ! The plugin support 4 byte ASN.
