### ISSUE TITLE
API requires "Device" field for Sessions whereas GUI does not

### ISSUE THREAD

**Issue by CmdrSharp** [k01ek/netbox-bgp#61]
**NetBox version**
v2.10-ldap

**Describe the bug**
When POST'ing via API to create a BGP Session, you need to specify a device - otherwise, you get:

```
{
    "device": [
        "This field is required."
    ]
}
```

This was not the case before. This is also not the case via GUI.

**Expected behavior**
The BGP Session should create without a device, as a device is not a required field.

**Comment by k01ek** [comment]
#66
