### ISSUE TITLE
Feature request: provider field in bgp sessions form

### ISSUE THREAD

**Issue by orester** [k01ek/netbox-bgp#68]
**Is your feature request related to a problem? Please describe.**
Not a problem but an useful feature for benefit from data which is already in netbox.

**Describe the solution you'd like**
Add an additonal field "Provider"  (using Circuits / Providers as a source) on all BGP sessions forms / reports (optional, because an iBGP session will not have any provider for example)

**Describe alternatives you've considered**
Use Name field for provider names which is for sure not the same after touching this 400+ times including all variants of provider names.

**Additional context**
![image](https://user-images.githubusercontent.com/22522988/141476101-7bf8ae02-8df8-4d9d-b13d-836b6a5a4e69.png)

**Comment by k01ek** [comment]
Hi @orester! Since NetBox 3.2 you can use Custom Object Fields for that.
