### ISSUE TITLE
Feature Request: Add fields for import and export policies

### ISSUE THREAD

**Issue by pspdbx** [k01ek/netbox-bgp#7]
Thank you very much for creating this plugin! Just what I was looking for to address a huge gap in the Netbox core model. We use import and export policies for every peer (for compliance), but are having trouble finding a good place to store that info in Netbox (custom fields are not a good fit). Can you please update your model to include fields to store the names of import and export policies? Both import and export policies can be a list of strings , for example ['BOGONS-REJECT', 'PRIVATE-PEER-IN'] , i.e. there could be more than one policy (order matters) for both import and export.

**Comment by k01ek** [comment]
Hi @pspdbx ! Glad to know that the plugin is helpful for you. I planed to add this functionality later.

**Comment by pspdbx** [comment]
Thank you @k01ek! My team is super excited to try this plugin out. We are going to try to deploy this in our Netbox in the coming days and explore the GUI and API. 

With the import and export policies fields, it would really meet our requirements fully, and shape how some of our CLI tools, and other services consume the BGP peering data (which currently doesn't live in a structured form). 

Thanks again for working on this feature; we are eagerly waiting for it! 😄

**Comment by pspdbx** [comment]
Hi @k01ek , could https://github.com/k01ek/netbox-bgp/blob/main/netbox_bgp/views.py#L91 cause performance problems when there are a large number of entries in the BGP session table?

**Comment by k01ek** [comment]
Hi @pspdbx ! I don' know. I need to test this issue. How many session do you have?

**Comment by pspdbx** [comment]
> Hi @pspdbx ! I don' know. I need to test this issue. How many session do you have?

Approximately 10,000. After reading more about https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/views/generic.py#L74 ,  I think it's going to be fine.
