### ISSUE TITLE
Not working UI actions for non-superusers

### ISSUE THREAD

**Issue by proudbro** [k01ek/netbox-bgp#71]
**NetBox version**
3.0.10

**Describe the bug**
Regardless of whether specified permissions on plugin models they are don't work with non-superusers via UI.
There are hidden items in menu. 

**To Reproduce**
1. Go to admin panel -> permissions
2. Create permissions on BGP plugin models
3. Assign permission to non superuser 
4. Relogin to this user and try to create smth, for example _sessions_ 

**Expected behavior**
You can fall into the list of sessions

**Screenshots**
![image](https://user-images.githubusercontent.com/60253505/142224134-89bb4b3a-dc98-4ae5-a095-e8db93631894.png)
I suppose:
![image](https://user-images.githubusercontent.com/60253505/142225262-324ec9e1-8ccd-4a5e-aefd-ab9b5ec1a02b.png)

**Additional context**
Permissions work if you try to do it directly via URL: `https://<your_netbox>/plugins/bgp/session/`

Problem can be there: `https://github.com/k01ek/netbox-bgp/blob/main/netbox_bgp/navigation.py`
Pls, fix

**Comment by Trunkol** [comment]
We are facing the same issues with Netbox 2.11.12/3.0.10
