### ISSUE TITLE
Feature Request: Deprecate ASN model in favor of NetBox 3.1.0 ASN model

### ISSUE THREAD

**Issue by ryanmerolle** [k01ek/netbox-bgp#82]
**Is your feature request related to a problem? Please describe.**
NetBox 3.1.0 added the new ASN model allowing you to specify multiple sites to an ASN.  It would be ideal to leverage said model, and extend it in the same way you have within this BGP plugin.

**Describe the solution you'd like**
Deprecate the custom plugin model for ASNs and leverage the core NetBox model.  The only difference between the two is that the core model allows for:
- multiple sites per ASN
- tenant group assignments for ASNs
- An RIR association

IE that means no current attribute of the netbox-plugin model would be missing.

Sessions would just be linked to the NetBox core model of ASN.

**Describe alternatives you've considered**
Keep the two separate and continue confusion within the API and UI.

**Additional context**
N/A

**Comment by dteknet** [comment]
There's also a conflict between the native ASNTable and the plugins' ASNTable interface configuration settings.
The thing is that a native one has the 'asn' field that is representing the number of AS, while the plugin has the 'number' field for that purpose. Each time I'm changing the table display setting for each table it rewrites the settings for another one.

![image](https://user-images.githubusercontent.com/65331309/165264276-2256b26c-e1fa-4fc0-871d-05eff6023b12.png)
![image](https://user-images.githubusercontent.com/65331309/165264364-f830081f-d0e4-4a36-b897-c0ca3f2b864d.png)

**Comment by k01ek** [comment]
Hi @peterbaumert ! Thanks for interest! I am gonna to make it this week.

**Comment by peterbaumert** [comment]
Nice will try first thing monday :)
