### ISSUE TITLE
relation "netbox_bgp_asn" does not exist

### ISSUE THREAD

**Issue by jbparrish17** [k01ek/netbox-bgp#84]
Hello,

I have recently installed Netbox 3.1.8 on Ubuntu 20.04 LTS with PostrgreSQL 12.9. I have installed the netbox-bgp plugin with pip, defined the netbox_bgp plugin in the configuration.py file, and restarted Netbox. I am now able to see the BGP plugin in the web interface, but when I navigate to /plugins/bgp/asn (or any other URLs under the plugin) I am met with a server error:

Server Error
A database programming error was detected while processing this request. Common causes include the following:

Database migrations missing - When upgrading to a new NetBox release, the upgrade script must be run to apply any new database migrations. You can run migrations manually by executing python3 manage.py migrate from the command line.

Unsupported PostgreSQL version - Ensure that PostgreSQL version 9.6 or higher is in use. You can check this by connecting to the database using NetBox's credentials and issuing a query for SELECT VERSION().

The complete exception is provided below:

<class 'django.db.utils.ProgrammingError'>

relation "netbox_bgp_community" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "netbox_bgp_community"
                                          ^

Python version: 3.8.10
NetBox version: 3.1.8

This error occurs for these URLs:
/plugins/bgp/asn/
/plugins/bgp/session/
/plugins/bgp/community/
/plugins/bgp/routing-policy/
/plugins/bgp/peer-group/

Is this just a misconfiguration on my part?

**Comment by nahun** [comment]
I don't think you ran the database migrations after enabling the plugin. See the NetBox docs on installing plugins: https://netbox.readthedocs.io/en/stable/plugins/#installing-plugins

The docs for this plugin should probably mention the database migrations part though too.

**Comment by jbparrish17** [comment]
Thank you. That's exactly what I was missing. Should have read the plugin docs.
