### ISSUE TITLE
Search/filter in UI is broken

### ISSUE THREAD

**Issue by ryanmerolle** [k01ek/netbox-bgp#98]
**NetBox version**
3.2.5

**Describe the bug**

**To Reproduce**
1. Filter an ASN on status and select multiple statuses
2. Click search
3. Observer the search for this function is handled with "AND" logic instead of "OR".  IE an ASN can only have one status, so the logic when using the multi-select option should use "OR" logic.

**Expected behavior**
Selecting multiple of the same field in a multiset not refernecing a many to many relationship like site or tenant to ASN.

**Additional context**
This seems a problem for other plugins and for most areas of the netbox-bgp search.

**Comment by jwbensley** [comment]
I am having the same problem with latest version of this BGP plugin and NetBox v3.3.2.

I have two example BGP sessions, and I want to search for the one with "v4" in the name:

![image](https://user-images.githubusercontent.com/1025875/198330049-6920568f-e5a1-47de-ad2d-5b907a1bd589.png)

Searching for "v4" generates and error:

![image](https://user-images.githubusercontent.com/1025875/198330849-25268ff9-8f26-4e6e-a0c2-ba7b2a3a73b9.png)

![image](https://user-images.githubusercontent.com/1025875/198331151-5514d5aa-abab-4f87-8e12-25af65c0a540.png)

I have also tried all of the follow REST API option and none of them work:

```
http://localhost:8080/api/plugins/bgp/bgpsession/?name__ct=v4
http://localhost:8080/api/plugins/bgp/bgpsession/?name__icontains=v4
http://localhost:8080/api/plugins/bgp/bgpsession/?q=name:*v4*
http://localhost:8080/api/plugins/bgp/bgpsession/?q=name:%v4%
http://localhost:8080/api/plugins/bgp/bgpsession/?q=v4
```
